version: "3.7"
services:
  mongodb:
    container_name: mongo-container
    image: mongo:4.2.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_DATABASE: root-db

    volumes:
      - ./config_init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
